language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
  slack: duraspace:vOBySuKUwM95j2kfbwh0SNxq
install:
  - mvn install -DskipTests --batch-mode
script:
  - mvn test -DskipIntTests
sudo: true
env:
  global:
    - secure: "j62ojMvGpgh0RU/bodZCJclcFdW8aQumaAbtNKAQ/M6fURu7uxQQl7xY63nXaB/R/WzVWjQtzoWCTysK7yrXIddZJ62MxkNbY6M7JSgwnP1t9Xi/yqQxxXMiRdW9M5gsf7WreUYME/wpggS2EEFNqX6bakQBl2/uhukOmfebCO0="
    - # ^^ SONATYPE_USERNAME
    - secure: "db3tDu+l/hN/064jOJyPfK1rSbLtbJV6GLNM3N1s3qf4i/yYpD6nW9O9l3aKnqRFC1hWTXwWe8aGfhNaCMWqpNC8iLeOSWc34DVQ52VwTxdPhDF2RuqfUby8+3GZHK4I5mUtXtXF6bVI1sO2PXAZ29VLaNkCN756P037apo4/gw="
    - # ^^ SONATYPE_PASSWORD
    - secure: "LTs/ZAJfZwxDFGpRtJ0xWnG5GWHu+DYrEg8mIEKhVDT4fLc+AIo8ZopNbLXIMCZUGbuebqEt2SyVM3ASgYiYUk12YPD37pL3415tmW8RevZvtyHQbK8hlE/8PzAxA8jh7a21QaP73F9pyvGjz5hq/2wDYgyYCQDzfXgMEN9y3Mg="
    - # ^^ GPG_KEY_NAME
    - secure: "HLMvMVB61micIKUaILeojgqQGPJyXL4rJu3eHrhsNfTHGax9HVkogW6zVz05hSNpMlzDmGmcvSFFkLsnd+eLOJ2h8OF7yFLCMxgH+WRxwfIym5ua2o/0cGtt/fNutSZ7QuQoJxbC3Npg+6RLCut+43FI5wylcD77P00kyYsX59I="
    - # ^^ GPG_PASSPHRASE
after_success:
  - chmod +x resources/travis/*.sh
  - ./resources/travis/before-deploy.sh
  - ./resources/travis/deploy.sh
